package io.fluidsonic.compiler

import org.jetbrains.kotlin.cli.common.*


/** The result of a Kotlin compilation. */
public data class CompilationResult(
	/** The exit code indicating success or failure. */
	val exitCode: ExitCode,
	/** Files generated by annotation processors during compilation. */
	val generatedFiles: Collection<GeneratedFile>,
	/** Messages emitted during compilation. */
	val messages: List<CompilationMessage>
)
