package io.fluidsonic.compiler

import java.io.*


/** A file generated by an annotation processor during compilation. */
public data class GeneratedFile(
	/** The text content of the generated file. */
	val content: String,
	/** The relative path of the generated file. */
	val path: File
)
